# Generated by Django 4.1 on 2023-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcategory',
            name='image_link',
            field=models.CharField(max_length=40),
        ),
    ]
