# Generated by Django 4.1 on 2023-06-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_prodcategory_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcategory',
            name='category',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='prodcategory',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
