# Generated by Django 4.1 on 2023-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_prodcategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodcategory',
            name='image_link',
        ),
        migrations.AddField(
            model_name='prodcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='prodcategory-img/'),
        ),
    ]
