# Generated by Django 4.1 on 2023-06-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_prodcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcategory',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prodcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='static/media/images/'),
        ),
    ]
