# Generated by Django 4.1 on 2023-06-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_prodcategory_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
