# Generated by Django 4.1 on 2023-06-18 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0011_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(default='No Product', max_length=16)),
                ('totalprice', models.DecimalField(decimal_places=2, default=200.0, max_digits=5)),
                ('description', models.CharField(max_length=60)),
                ('purchased', models.BooleanField()),
                ('date_created', models.DateField(null=True)),
                ('date_updated', models.DateField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.prodcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
