# Generated by Django 4.1 on 2023-06-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_cart2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Cart2',
        ),
    ]
