# Generated by Django 4.1 on 2023-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_cart_qnty'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcategory',
            name='link',
            field=models.SlugField(default='link'),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.SlugField(default='link'),
        ),
    ]
